default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: asset_database
  username: asset_user
  password: ottersarecool
  host: 127.0.0.1
  port: 3306

test:
  <<: *default
  database: asset_database
  username: asset_user
  password: ottersarecool
  host: 127.0.0.1
  port: 3306

production:
  <<: *default
  database: asset_database
  username: asset_user
  password: ottersarecool
  host: 127.0.0.1
  port: 3306
